version: 1.7.6-{build}-{branch}
os: Visual Studio 2017

configuration: Release

before_build:
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n"
- git config --global user.email "appveyor@appveyor.com"
- git config --global user.name "AppVeyor"
- git submodule update --init --recursive
- mkdir LiveSplit\LiveSplit.Core\Updates\GitInfo
- git describe --dirty --always --long --tags > LiveSplit\LiveSplit.Core\Updates\GitInfo\version.txt
- git rev-parse --abbrev-ref HEAD > LiveSplit\LiveSplit.Core\Updates\GitInfo\branch.txt
- git rev-parse HEAD > LiveSplit\LiveSplit.Core\Updates\GitInfo\revision.txt
- nuget restore LiveSplit\LiveSplit.sln

build_script:
- msbuild LiveSplit\LiveSplit.sln /verbosity:minimal /p:NoWarn=1591 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

notifications:
- provider: Email
  to:
  - spapushin@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

test:
  assemblies: LiveSplit\LiveSplit.Tests\bin\Release\LiveSplit.Tests.dll

after_build:
- ps: >-
    if (!"$env:APPVEYOR_PULL_REQUEST_TITLE" -and ("$env:APPVEYOR_REPO_BRANCH" -eq "master"))
    {
        $BUILD_NAME = "LiveSplitDevBuild.zip"

        mkdir .\LiveSplit\bin\Release\Resources

        cp .\LiveSplit\Resources\SplitsFile.ico .\LiveSplit\bin\Release\Resources\
        cp .\LiveSplit\Resources\LayoutFile.ico .\LiveSplit\bin\Release\Resources\

        cd LiveSplit\bin\Release

        Get-ChildItem * -Include *.xml -Recurse | Remove-Item
        Get-ChildItem * -Include *.pdb -Recurse | Remove-Item

        cd ..\..\..\

        7z a $BUILD_NAME .\LiveSplit\bin\Release\*

        git clone -q "https://github.com/LiveSplit/LiveSplit.github.io.git"
        cd LiveSplit.github.io
        git checkout -q artifacts
        mv ../$BUILD_NAME . -force
        git add $BUILD_NAME
        git commit --amend -m "Add Development Build"
        git push --force -q origin artifacts
        
    }
